"""initial_tables

Revision ID: 70a542d2df6b
Revises: 
Create Date: 2026-07-17 10:39:58.173064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260717_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teachers_username'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_auth_email_challenges_email'), table_name='auth_email_challenges')
    op.drop_index(op.f('ix_auth_email_challenges_expires_at'), table_name='auth_email_challenges')
    op.drop_index(op.f('ix_auth_email_challenges_purpose'), table_name='auth_email_challenges')
    op.drop_index(op.f('ix_auth_email_challenges_purpose_email'), table_name='auth_email_challenges')
    op.drop_table('auth_email_challenges')
    op.drop_index(op.f('ix_session_visual_observations_observation_id'), table_name='session_visual_observations')
    op.drop_index(op.f('ix_session_visual_observations_segment_id'), table_name='session_visual_observations')
    op.drop_index(op.f('ix_session_visual_observations_session_id'), table_name='session_visual_observations')
    op.drop_index(op.f('ix_session_visual_observations_vlm_status'), table_name='session_visual_observations')
    op.drop_table('session_visual_observations')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_session_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_lessons_owner_user_id'), table_name='lessons')
    op.drop_constraint(op.f('fk_lessons_owner_user_id_users'), 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'owner_user_id')
    op.drop_index(op.f('ix_session_students_student_id'), table_name='session_students')
    op.drop_constraint(op.f('uix_session_student'), 'session_students', type_='unique')
    op.drop_column('session_turns', 'slide_no')
    op.drop_column('session_turns', 'class_elapsed_sec')
    op.drop_index(op.f('ix_sessions_teacher_id'), table_name='sessions')
    op.drop_column('sessions', 'teacher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('teacher_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_sessions_teacher_id'), 'sessions', ['teacher_id'], unique=False)
    op.add_column('session_turns', sa.Column('class_elapsed_sec', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('session_turns', sa.Column('slide_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uix_session_student'), 'session_students', ['session_id', 'student_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_session_students_student_id'), 'session_students', ['student_id'], unique=False)
    op.add_column('lessons', sa.Column('owner_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_lessons_owner_user_id_users'), 'lessons', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_lessons_owner_user_id'), 'lessons', ['owner_user_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_token_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_addr', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('auth_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_sessions_pkey')),
    sa.UniqueConstraint('session_token_hash', name=op.f('uq_auth_sessions_token_hash'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_session_token_hash'), 'auth_sessions', ['session_token_hash'], unique=False)
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_table('session_visual_observations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('observation_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('segment_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('window_start_sec', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('window_end_sec', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slide_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('thumbnail_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('vlm_status', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('vlm_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('precheck_passed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('session_visual_observations_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('session_visual_observations_pkey'))
    )
    op.create_index(op.f('ix_session_visual_observations_vlm_status'), 'session_visual_observations', ['vlm_status'], unique=False)
    op.create_index(op.f('ix_session_visual_observations_session_id'), 'session_visual_observations', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_visual_observations_segment_id'), 'session_visual_observations', ['segment_id'], unique=False)
    op.create_index(op.f('ix_session_visual_observations_observation_id'), 'session_visual_observations', ['observation_id'], unique=False)
    op.create_table('auth_email_challenges',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('code_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('verified_token_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('consumed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('attempt_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('send_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('last_sent_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_email_challenges_pkey'))
    )
    op.create_index(op.f('ix_auth_email_challenges_purpose_email'), 'auth_email_challenges', ['purpose', 'email'], unique=False)
    op.create_index(op.f('ix_auth_email_challenges_purpose'), 'auth_email_challenges', ['purpose'], unique=False)
    op.create_index(op.f('ix_auth_email_challenges_expires_at'), 'auth_email_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_email_challenges_email'), 'auth_email_challenges', ['email'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=64), server_default=sa.text("'实习教师'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('teachers_pkey'))
    )
    op.create_index(op.f('ix_teachers_username'), 'teachers', ['username'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=64), server_default=sa.text("'实习教师'::character varying"), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###
